### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by hakostra**

### CODE REVIEW

**Comment by hakostra** [comment]
Hi @swenczowski 

Just want to draw attention towards the second commit "Fix correcting wrong INTENT(out) in subroutines for specific level".

I do not think that the Intel and GNU compilers make any difference if the intent is wrong in these cases where I corrected it here, because everything apparently works great with those. The mistake was found running NAG compiler in Debug mode, in which the compiler apparently fills every INTENT(out) with NaN before the subroutine start, in order to smoke out such problems. This meant that certain arrays was filled with NaN at the coarsest levels and only the finest had real data in it.

Another thing I want to point out is that many places where there is an intermediate "XXXXX_level" subroutine, this is not required and I would not make it in that way again. I would just drop it completely and have "XXXXX" and "XXXXX_grid" (e.g. `calcauavaw` and `calcauavaw_grid`). Many of these blocking routines was programmed early before I really figured out the current practices. I think I will remove the intermedte "XXXXX_level" subroutines in a separate commit/PR where applicable.

**Comment by swenczowski** [comment]
Thank you for the comments. Taken note of.

**Comment by swenczowski** [comment]
Considering also the fully configured CMake presets for NAG, I was wondering if there were any plans to also use the NAG compiler in the automated testing workflows of mglet-base?

**Comment by hakostra** [comment]
Not automatically, but I have a license on my workstation I can use to run tests manually when necessary. The current status is that with the changes in this PR implemented, 5 out of 11 tests pass.

**Pull request merged**
