### PR TITLE
Scalar statistics units computation

### PR DESCRIPTION
**Pull request by hakostra**
@swenczowski

### CODE REVIEW

**Comment by swenczowski** [comment]
Accordingly, one would enter the unit of the scalar field in the "parameters.json", the unit would appear as one attribute in  `scalar_t`, and the fields objects would be created with the corresponding unit. Is that the idea?

If yes, then I fully agree.

**Comment by hakostra** [comment]
That feature of reading units from parameters.json is not yet there - but can of course be added easily. Until then the units will at least be consistent (the scalar field itself and the 1st order average are dimensionless - it was a bit strange that the newly added statistics introduced the units of temperature).

**Comment by swenczowski** [comment]
Of course, but then it makes sense to go ahead with this PR as a preparation for the further steps.

**Comment by swenczowski** [comment]
@hakostra @javierebb

Dear Håkon, Dear Javier,

Firstly, I am impressed by the existing infrastructure for *.json parsing! 

Secondly, I used this infrastructure to build up on this branch and write a few lines, which allow us to extract the scalar unit from the *.json file, if it is provided. @javierebb: Please, find the branch at 

https://github.com/tum-hydromechanics/tum-mglet-base/tree/simon/scastat-units

Our suggestion is that we use these first steps to enrich the scalar statistics by dimensionally reasonable units. That would allow us to ensure better understandability of result files and provide a further check for dimensional correctness when it comes to spatial derivatives. Do you agree?

If yes from sides of @hakostra, @javierebb, please, start the development as discussed.

Best regards,

Simon

**Comment by hakostra** [comment]
I take it that I shall merge this then. Awaiting another PR from either of you with follow-up.

**Comment by swenczowski** [comment]
Great. Further development on this basis will take place in our branch (https://github.com/tum-hydromechanics/tum-mglet-base/tree/simon/scastat-units) and a corresponding PR will follow.

**Pull request merged**
