### PR TITLE
Idea to address errors resulting from missing G field in DNS

### PR DESCRIPTION
**Pull request by swenczowski**
Dear MGLET developers,

I encountered some issues in the reading phase, if the data is from a DNS simulation:

> ERRR: 0 MGLET FATAL ERROR
> ERRR: 0 CODE:    254
> ERRR: 0 MESSAGE: MGLET Error
> ERRR: 0 FILE:    /home/swenczowski/Development/tum-mglet-base-stastistics/src/core/hdf5common_mod.F90
> ERRR: 0 LINE:    287
> 
>  Group creation failed: G 

The present PR is just an idea how to possibly address that. Please, however, exclude ".github/workflows/build.yml" from a possible merge.

Best regards,

Simon

### CODE REVIEW

**Comment by hakostra** [comment]
First of all, when making a PR make sure it is a single, clean commit on top of master. I cannot merge this as-is since it contains several unrelated commits.

Secondly, I struggle to see the problem you are attempting to solve. I constructed a variant of Taylorvortex_2D, where I computed 100 timesteps with "lesmodel": "none", and then continued with "read": "true" and another 100 timesteps of "lesmodel": "wale". That worked like a charm.

**Comment by swenczowski** [comment]
Dear Håkon,

as I was not sure if that is the right way to address the issue, I did not fully elaborate a pull request. Sorry for that. 

The problem should occur if you conduct a simulation with "lesmodel": "none" and then continue (with "read": "true") the simulation with "lesmodel": "none". In that case, I observed that MGLET would still try to read the G field, which is not present.

Can you confirm that?

Best regards,

Simon

**Comment by hakostra** [comment]
I do not manage to reproduce such a behavior. Can you send be (by email) a small test case that reproduce the issue?

**Comment by swenczowski** [comment]
I also fail to reproduce the problem using exclusively the new "mglet-base". What I missed to see was that even in the case of a DNS simulation, "mglet-base" writes out a uniform-value field "G" in its "fields.h5". This field is then successfully read in again and the simulation starts perfectly.

Issues surface if one tries to continue an "mglet-8.3" case with "mglet-base". I had not kept in mind that the "fields.h5" that was use had not been generated by "mglet-base" itself but was inherited from the older version. In that case, the "G" field is missing for DNS.

Sorry for not correctly identifying that as a backward compatibility issue. 

I do not know if you want to pursue compatibility in this concern, but I could imagine it to be useful.

**Pull request closed without merging**
